import random 

names = [" Graceland",
" Definitely Maybe",
" Band",
" Doors",
" Low",
" Who’s Next",
" Out of Time",
" Trout Mask Replica",
" Jagged Little Pill",
" Tommy",
" Marquee Moon",
" Odelay",
" Five Leaves Left",
" Smiths",
" Parallel Lines",
" Transformer",
" Legend",
" Led Zeppelin",
" After the Goldrush",
" Are You Experienced?",
" Thriller",
" Loveless",
" Bridge Over Troubled Water",
" Hotel California",
" Moon Safari",
" Performance and Cocktails",
" Ten",
" St Dominic’s Preview",
" Purple Rain",
" Little Earthquakes",
" Tapestry",
" Man Who",
" Mellon Collie & the Infinite Sadness",
" Debut",
" Talk on Corners",
" Moondance",
" Woodface",
" II",
" So",
" Crosby Stills & Nash",
" Sticky Fingers",
" A Love Supreme",
" Goodbye Yellow Brick Road",
" Hounds of Love",
" Songs in the Key of Life",
" Otis Blue",
" Synchronicity",
" It Takes a Nation of Millions to Hold us Back",
" Harvest",
" Disintegration",
" Parklife",
" A Night at the Opera",
" Licensed to Ill",
" Moby Grape ",
" Grace",
" Tubular Bells",
" American Beauty",
" Van Halen",
" Master of Puppets",
" Déjà vu",
" Back in Black",
" Hysteria",
" Siamese Dream",
" August and Everything",
" Physical Graffiti",
" Garbage",
" Doolittle",
" Gold: Greatest Hits",
" Court and Spark",
" Houses of the Holy",
" Aja",
" Help!",
" Like a Prayer",
" Bat Out of Hell",
" War",
" Hot Rats",
" Everybody Knows This is Nowhere",
" Sings for Only the Lonely",
" Clear Spot",
" Freewheelin’",
" Imagine",
" Stephen Stills",
" Close to the Edge",
" Pink Moon",
" Fun House",
" Another Side of",
" Meat is Murder",
" Screamadelica",
" Chronic",
" Appetite for Destruction",
" 3 Feet High and Rising",
" Green",
" Slanted and Enchanted",
" Are the Village Green Preservation Society",
" Blood Sugar Sex Magik",
" Innervisions",
" Rum Sodomy and the Lash",
" Enter the Wu Tang (36 Chambers)",
" Aladdin Sane",
" Axis: Bold as Love",
" For the Roses",
" Songs of",
" Older",
" Parade",
" This Year’s Model",
" In a Silent Way",
" Quadrophenia",
" Sketches of Spain",
" If Only I Could Remember my Name",
" 1962",
" Notorious Byrd Brothers",
" Lexicon of Love",
" Born in the USA",
" Fresh Fruit for Rotting Vegetables",
" Life’s Rich Pageant",
" Piper at the Gates of Dawn",
" Americana",
" Again",
" Machine Head",
" Dog Man Star",
" Surfer Rosa",
" White on Blonde",
" Steve McQueen",
" Dusty in Memphis",
" Safe as Milk",
" Captain Fantastic and the Brown Dirt Cowboy",
" Surrealistic Pillow",
" New York",
" Dig Your Own Hole",
" Toys in the Attic",
" No Other",
" Live!",
" Clash",
" Setting Sons",
" Disraeli Gears",
" Pornography",
" Fleetwood Mac (1975)",
" Heroes",
" New Adventures in Hi Fi",
" Avalon",
" # 1 Record",
" Bringing it all Back Home",
" September of my Years",
" Boston",
" Hatful of Hollow",
" In the Court of the Crimson King",
" Sandanista!",
" On the Beach",
" Check Your Head",
" Younger Than Yesterday",
" Dookie"]

names2 = [" Erotica",
" Faith",
" Tea for the Tillerman",
" We’re Only In it for the Money",
" Life After Death",
" Hats",
" Out of the Blue",
" Slippery When Wet",
" Paranoid",
" Birth of the Cool",
" Music for the Masses",
" Number of the Beast",
" I Never Loved a Man the Way I Love You",
" Sailor",
" Come On Over",
" Eliminator",
" Live at Leeds",
" Köln Concert",
" Wild the Innocent and the E Street Shuffle",
" In the Wee Small Hours",
" Genius ",
" III",
" At Fillmore East/Fillmore Concerts",
" Generation Terrorists",
" Let’s Get it On",
" the Dreaming",
" Boys for Pele",
" Savage",
" Swing Easy!",
" John Barleycorn Must Die",
" Dream of the Blue Turtles",
" Workingman’s Dead",
" Bring it on",
" Elton John",
" Swordfishtrombones",
" Outlandos D’Amour",
" Anthem of the Sun",
" Here Come the Warm Jets",
" Times They are a Changin’",
" On How Life is",
" Sweet Dreams (Are Made of This)",
" Psychocandy",
" Rock ‘n’ Roll Animal",
" Burnin’",
" the Cars",
" Seal (1991)",
" Bandwagonesque",
" Aftermath",
" 1984",
" Once Upon a Time",
" Genius of",
" Blues Breakers with Eric Clapton",
" My Favorite Things",
" Tumbleweed Connection",
" Stop Making Sense",
" Wrecking Ball",
" 77",
" Doggystyle",
" Reggatta da Blanc",
" Miles Smiles",
" Fly Like an Eagle",
" Foo Fighters",
" Story",
" II",
" Genius of Modern Music Vols 1 & 2",
" Saxophone Colossus",
" Hangman’s Beautiful Daughter",
" A Walk Across the Rooftops",
" My Own Prison",
" …and Justice for All",
" Zuma",
" Atomic Mr Basie",
" Copperhead Road",
" Fullfillingness’ First Finale",
" Low End Theory",
" Smiley Smile",
" Vs.",
" Complete Savoy Sessions",
" Rolling Stones",
" Spirit of Eden",
" Kick",
" There Goes Rhymin’ Simon",
" Shoot Out the Lights",
" I Want You",
" Healer",
" Nebraska",
" Black Saint and the Sinner Lady",
" No More Heroes",
" Saucerful of Secrets",
" Bossanova",
" II",
" Veedon Fleece",
" Risqué",
" Be Yourself Tonight",
" Maiden Voyage",
" Peter Green’s…",
" Tragic Kingdom",
" Blind Faith",
" Oh Mercy",
" Buena Vista Social Club",
" Revenge",
" This Nation’s Saving Grace",
" Dressed to Kill",
" For Everyman",
" Downward Spiral",
" Club Classics Vol 1",
" Fear of Music",
" Rastaman Vibration",
" Meets Ben Webster",
" Sunflower",
" Paid in Full",
" Genius Hits the Road",
" Music From Big Pink",
" Showcase",
" Man and His Music (compilation)",
" Arc of a Diver",
" I’m Alive",
" These Days",
" Up",
" Be Here Now",
" At Newport (released 1957)",
" Sinatra at the Sands",
" Kick Inside",
" Trouble Man",
" Yield",
" Waltz for Debby",
" Big Willie Style",
" African Herbsman",
" Little Criminals",
" Sailin’ Shoes",
" My Funny Valentine",
" Sixteen Stone",
" Original Film Soundtrack (1968)",
" George & Ira Gershwin Songbook",
" Goodbye Jumbo",
" Blood & Chocolate",
" Lonely at the Top (compilation)",
" Milestones",
" Midnight Love",
" Various Artists",
" Body & Soul (compilation)",
" Young Americans",
" Permanent Vacation",
" the Fabulous…",
" Country Life",
" Heaven Up Here",
" Kick Out the Jams",
" Avalon Sunset",
" Complete & Unbelievable: the Dictionary of Soul",
" Keep the Faith",
" Sings the Cole Porter Songbook",
" Mingus Mingus Mingus Mingus Mingus",
" Sheer Heart Attack",
" Spice",
" Waiting for the Sun",
" I’m Your Man",
" Kaya",
" Night and Day",
" Here My Dear",
" Worker’s Playtime",
" Songs of Love & Hate",
" Tres Hombres",
" In Search of the Lost Chord",
" Eden",
" Gaucho",
" Last Time Around",
" Hypocrisy is the Greatest Luxury",
" Starsailor",
" New Boots & Panties",
" Pretender",
" Oar",
" Can’t Slow Down",
" Sky is Crying",
" Stand Up",
" What’s the 411?",
" Band on the Run",
" Hello & Goodbye",
" Mr Fantasy",
" Bedtime Stories",
" Chirping Crickets",
" Songs from the Wood",
" In the Dark",
" Reggae Greats (compilation)",
" Singles 1969",
" River",
" Here’s…",
" Round About Midnight",
" Lady in Autumn",
" One of These Nights",
" Band of Gypsys",
" One Step Beyond",
" Money Jungle",
" Janet",
" Burn",
" Full Moon Fever",
" Pink Flag",
" Black and Blue",
" Damn the Torpedoes",
" Rocks",
" Teaser & the Firecat",
" King of America",
" Darkness at the Edge of Town",
" Baduism",
" Collective Soul",
" Unleashed in the East",
" Nice ‘n’ Easy",
" Republic",
" Stranded",
" Ellington Indigos",
" Kate & Anna McGarrigle",
" Modern Sounds in Country & Western Music",
" Wild Wood",
" Damned Damned Damned",
" Happy Trails",
" Face to Face",
" Last Record Album",
" From the Mars Hotel",
" Bellybutton",
" Aretha Now",
" Original Broadway Cast (1956)",
" Organ Grinder Swing",
" Pieces of the Sky",
" Hello I Must be Going",
" Dixie Chicken",
" Sonny Rollins Vol 2",
" Shift Work",
" Bare Wires",
" II",
" Steel Wheels",
" Soul Album",
" Travels",
" Vivid",
" Our Man in Paris",
" Hot Buttered Soul",
" This Was",
" Family That Plays Together",
" Kill ‘Em All",
" Together Alone",
" No Need to Argue",
" Nashville Skyline",
" Operation Radication",
" Your Arsenal",
" Sail Away",
" E 1999 Eternal",
" Sidewinder",
" I Do Not Want What I Have Not Got",
" Live at the Regal",
" Song Remains the Same",
" Big Ones",
" Stanley Road",
" Between the Lines",
" Crown of Creation",
" Bone Machine",
" X",
" Late for the Sky",
" After Bathing at Baxters",
" One Size Fits All",
" Word Gets Around",
" Dreadlocks Dread",
" Making Movies",
" Substance",
" Strangeways Here We Come",
" For Those About to Rock We Salute You",
" For Your Pleasure",
" Hokey Pokey",
" Apostrophe (‘)",
" Music in a Doll’s House",
" Volunteers",
" Song for My Father",
" Caravanserai",
" Nine Lives",
" Cracked Rear View Mirror",
" Stutter",
" the Scream",
" East Side Story",
" Nick of Time",
" Come Fly With Me",
" Fear of a Black Planet",
" Being There",
" Elvis Presley (1956)",
" Gilded Palace of Sin",
" 52nd Street",
" Please Please Me",
" Document",
" Grand Prix",
" Low Spark of the High Heeled Boys",
" Dread Inna Babylon",
" Pills ‘n’ Thrills & Bellyaches",
" Permanent Waves",
" King of the Delta Blues Singers",
" His Band & Street Choir",
" Desperado",
" Pearl",
" Cross of Changes",
" Secrets",
" Purple",
" Ella & Louis",
" Odyssey & Oracle",
" A Hard Road",
" With a Little Help From My Friends",
" Dare",
" Equal Rights",
" Sings the Rodgers & Hart Songbook",
" Sings Great Soul Ballads",
" In My Tribe",
" Music of My Mind",
" Wish",
" Smash",
" Holland",
" Bert Jansch (1965)",
" Slim Shady LP",
" Greetings from Asbury Park NJ",
" Time Out of Mind",
" La’s",
" If You’re Feeling Sinister",
" One for All",
" New Jersey",
" Phaedra",
" Spirit",
" I Still Believe in You",
" Blood Sweat & Tears (2nd Album)",
" Strictly Personal",
" Friends",
" Complete Live at the Plugged Nickel 1965",
" Love Chronicles",
" Rumor & Sigh",
" Beautiful Freak",
" Tell Mama",
" On the Threshold of a Dream",
" Offramp",
" Southern Harmony & the Musical Companion",
" I’ve Been Expecting You",
" Another Green World",
" Jailbreak",
" Aoxomoxoa",
" 154",
" Brave New World",
" At Folsom Prison",
" Eagles",
" Got My Mojo Workin’",
" Eat a Peach",
" Duke",
" Eve6",
" Miseducation of…",
" Bless the Weather",
" Grand Illusion",
" In Rock",
" Impressions",
" Unhalfbricking",
" Original Film Soundtrack",
" More Songs About Buildings and Food",
" 12 Songs",
" Euphoria",
" It’s Too Late to Stop Now",
" Armatrading",
" Coming Up",
" Aqualung",
" Daydream Nation",
" Space Oddity",
" Copper Blue",
" Damn Right I Got the Blues",
" Nimrod",
" Dire Straits",
" Madcap Laughs",
" Stage Fright",
" Under the Pink",
" Our Favourite Shop",
" Diamond Life",
" Trust",
" Wide Open Spaces",
" Talking with the Taxman About Poetry",
" I",
" Woman in Me",
" the Cat",
" Joe’s Garage",
" Volume 2",
" Randy Newman",
" Vitalogy",
" Feats Don’t Fail Me Now",
" Division Bell",
" Sparkle & Fade",
" Mezzanine",
" Pretenders",
" Adore",
" Antichrist Superstar",
" Great Escape",
" CrazySexyCool",
" Celebrity Skin",
" Hergest Ridge",
" Follow the Leader",
" Whatever and Ever Amen",
" Ladies of the Canyon",
" Hello Nasty",
" Third/Sister Lovers",
" the Score",
" Manassas",
" Ready to Die",
" Vulgar Display of Power",
" 2112",
" No Fences",
" Whitney Houston",
" Crossroad: the Best of",
" Love is the Thing",
" Spirit ",
" Pump",
" Destroyer",
"52’s ",
" Solo Monk",
" Burgers",
" A Day at the Races",
" Ill Communication",
" Promenade",
" Mellow Gold",
" No Code",
" Backstabbers",
" Harvest Moon",
" Dream Letter (Live in London 1968)",
" Wheels of Fire",
" Ropin’ the Wind",
" Tattoo You",
" Scott 4",
" Desire",
" Heavy Soul",
" Load",
" Giant Steps",
" Rid of Me",
" Rattus Norvegicus",
" Daydream",
" Actually",
" Everywhere",
" Still Crazy After All These Years",
" To Bring You My Love",
" Eponymous",
" 13",
" You’ve Come a Long Way Baby",
" Boys Don’t Cry",
" Hejira",
" Bleach",
" Baby One More Time",
" Let’s Stay Together",
" Crash",
" Songs of Faith and Devotion Live",
" Play",
" In a Gadda da Vida",
" Surfacing",
" Porgy & Bess",
" Monster",
" Don’t Look Back",
" Unplugged",
" A Momentary Lapse of Reason",
" Globe Sessions",
" Dock of the Bay",
" Under the Table and Dreaming",
" Ben Folds Five",
" Full Moon Dirty Hearts",
" Piano Man",
" So Much for the Afterglow",
" Something/Anything",
" Suzanne Vega",
" Reckless",
" Aenima",
" October",
" What Does Anything Matter Anymore?",
" Backstreet Boys",
" Waiting for Columbus",
" Pop",
" Three Dollar Bill Y’all$",
" Uncle Meat",
" Oxygene",
" Peter Gabriel (3rd Album)",
" Ghost in the Machine",
" Moseley Shoals",
" Paris 1919 ",
" Before These Crowded Streets",
" I Want to See the Bright Lights Tonight",
" From the Choirgirl Hotel",
" Get Yer Ya Ya’s Out",
" Morrison Hotel",
" A Boy Named Goo",
" Ride the Lightning",
" Modern Dance",
" High Land Hard Rain",
" Heavy Weather",
" Korn",
" This is Hardcore",
" A Little South of Sanity",
" Solid Air",
" Hell Freezes Over",
" Tigerlily",
" Monk’s Music",
" Skylarking",
" International Velvet",
" Boy",
" Head on the Door",
" Welcome to the Pleasuredome",
" the Captain & Me",
" Car Wheels on a Gravel Road",
" Mutations",
" Pacific Ocean Blue",
" Seal (2nd Album) (1994)",
" 1999",
" Use Your Illusion I",
" Soul Cages",
" Yes I am",
" Film Soundtrack",
" Boy with the Arab Strap",
" Temple of Low Men",
" Come On Come On",
" Terrapin Station",
" Monkees",
" Blows Against the Empire",
" In it for the Money",
" C’mon Kids",
" Tusk",
" All Things Must Pass",
" Colour & the Shape",
" Colour of My Love",
" Kings of the Wild Frontier",
" Mud Slide Slim & the Blue Horizon",
" Shepherd Moons",
" Real Thing",
" Black Woman & Child",
" Invisible Touch",
" Soft Parade",
" Maybe You’ve Been Brainwashed Too",
" Look Sharp!",
" Trick of the Tail",
" Mr Lucky",
" Royal Scam",
" Life is Peachy",
" Film Soundtrack",
" Pilgrim",
" It’s My Life",
" Electric Warrior",
" Dry",
" Listen Without Prejudice Vol 1",
" Treasure",
" Lion and the Cobra",
" It’s Great When You’re Straight Yeah!",
" K",
" Closing Time",
" Europe ‘72",
" New Gold Dream (81 82 83 84)",
" Supposed Former Infatuation Junkie",
" English Settlement",
" Body & Soul",
" Ommadawn",
" Reading Writing & Arithmetic",
" Tonight’s the Night",
" Tellin’ Stories",
" Let it Be",
" Lust for Life",
" Savage Garden",
" New York Dolls",
" Come Clean",
" Flood",
" Stunt",
" She’s so Unusual",
" Elephant Mountain",
" Cheap Thrills",
" 461 Ocean Boulevard",
" Melissa Etheridge",
" Good Ol’ Boys",
" Gentlemen",
" Nothing Like the Sun",
" Low Life",
" Oranges and Lemons",
" ReLoad",
" Lamb Lies Down on Broadway",
" Ram",
" Undertow",
" Love",
" Cookin’",
" No Way Out",
" From the Cradle",
" 5150",
" Dizzy Heights",
" Marc Cohn",
" Live Rust",
" Laid",
" Second Coming",
" Technique",
" Selected Ambient Works 1985",
" Songs from the Big Chair",
" Rhythm Nation 1814",
" This Fire",
" Jazz Samba",
" Stand!",
" Evil Empire",
" 40oz to Freedom",
" Computer World",
" Hearts & Bones",
" Presence",
" Without You I’m Nothing",
" Turn! Turn! Turn!",
" A Wizard A True Star",
" Exodus",
" Fanmail",
" Marcus Garvey",
" Mermaid Avenue",
" Mingus at Antibes",
" Days of Future Passed",
" Chicago Transit Authority",
" Shooting at the Moon",
" Tupelo Honey",
" Deserter’s Songs",
" Sunday at the Village Vanguard",
" Slowhand",
" One World",
" Weld",
" Whitechocolatespaceegg",
" Back to Back",
" Third Eye Blind",
" At Carnegie Hall",
" Happy Sad",
" Songs for a Tailor",
" Me Against the World",
" Soul’s Core",
" Small Change",
" Moanin’",
" Trailer Park",
" Whatever",
" the Dance",
" Did I Shave My Legs for This?",
" Brilliant Corners",
" Speaking in Tongues",
" Songs from Northern Britain",
" Crime of the Century",
" Hard Promises",
" Private Dancer",
" Dizzy Up the Girl",
" Solitude Standing",
" Endless Summer",
" Wonderful and Frightening World of the…",
" Violent Femmes",
" If I Should Fall From Grace with God",
" Original Soundtrack",
" No Guru No Method No Teacher",
" There’s a Riot Goin’ On",
" Follow the Leader",
" Live Through This",
" Surrender",
" Central Reservation",
" Core",
" Paul Simon",
" Original Film Soundtrack (1955)",
" Superfly (Soundtrack)",
" This is my Truth Tell me Yours",
" Flaming Pie",
" Live 1966: the ‘Royal Albert Hall’ Concert",
" Atom Heart Mother",
" Speak & Spell",
" 3 + 3",
" the Good Will Out",
" Someday My Prince Will Come",
" Diamond Dogs",
" Freedom",
" No Secrets",
" Still Warm",
" Trinity Session",
" Todd"]




f = open("album.txt", "w", encoding='utf-8')
f1 = open("tracks.txt", "w", encoding='utf-8')

tr = 0

for i in range(200):
    tracknum = random.randint(1, 6)
    
    st = "{0}, {1}, {2}, {3};".format(i+1, random.randint(1, 100), random.randint(1970, 2000), names[random.randint(0, len(names)-1)])
    f.write(st)

    for j in range(tracknum):
        tr +=1
        st2 = "{0}, {1}, {2};".format(tr, names2[random.randint(0, len(names2)-1)], i+1)
        f1.write(st2)

        
f.close()
f1.close()
