import random 
names = ["The Beatles",
"Bob Dylan",
"Elvis Presley",
"The Rolling Stones",
"Chuck Berry",
"Jimi Hendrix",
"James Brown",
"Little Richard",
"Aretha Franklin",
"Ray Charles",
"Bob Marley",
"The Beach Boys",
"Buddy Holly",
"Led Zeppelin",
"Stevie Wonder",
"Sam Cooke",
"Muddy Watters",
"Marvin Gaye",
"The Velvet Underground",
"Bo Diddley",
"Otis Redding",
"U2",
"Bruce Springsteen",
"Jerry Lee Lewis",
"Fats Domino",
"Ramones",
"Nirvana",
"Prince",
"The Who",
"The Clash",
"Johnny Cash",
"Smokey Robinson & the Miracles",
"The Everly Brothers",
"Neil Young",
"Michael Jackson",
"Madonna",
"Roy Orbison",
"John Lennon",
"David Bowie",
"Simon and Garfunkel",
"The Doors",
"Van Morrison",
"Sly and the Family Stone",
"Public Enemy",
"The Byrds",
"Janis Joplin",
"Patti Smith",
"Run-DMC",
"Elton John",
"The Band",
"Pink Floyd",
"Queen",
"The Allman Brothers Band",
"Howlin' Wolf",
"Eric Clapton",
"Dr. Dre",
"The Grateful Dead",
"Parliament/Funkadelic",
"Aerosmith",
"The Sex Pistols",
"Metallica",
"Joni Mitchell",
"Tina Turner",
"Phil Spector",
"The Kinks",
"Al Green",
"Cream",
"The Temptations",
"Jackie Wilson",
"The Police",
"Frank Zappa",
"AC/DC",
"Radiohead",
"Hank Williams",
"The Eagles",
"The Shirelles",
"Beastie Boys",
"The Stooges",
"The Four Tops",
"Elvis Costello",
"The Drifters",
"Creedence Clearwater Revival",
"Eminem",
"James Taylor",
"Black Sabbath",
"2Pac",
"Gram Parsons",
"Jay-Z",
"The Yardbirds",
"Carlos Santana",
"Tom Petty",
"Guns N’ Roses",
"Booker T. and the MG’s",
"Nine Inch Nails",
"Lynyrd Skynyrd",
"Diana Ross and the Supremes",
"R.E.M.",
"Curtis Mayfield",
"Carl Perkins",
"Talking Heads"]

countries = ["USA", "Canada", "Great Britain", "Australia", "Sweden", "Ireland", "Japan", " Jamaica"]


f = open("group.txt", "w")

for i in range(len(names)):
    st = "{0}, {1}, {2}, {3};".format(i+1, names[i], random.randint(1, 35), countries[random.randint(0, 7)])
    f.write(st)
f.close()


