USE Lab01


DROP PROCEDURE GetTablesInfo;
GO

CREATE PROCEDURE GetTablesInfo AS
BEGIN
	SELECT TABLE_NAME
	FROM INFORMATION_SCHEMA.TABLES
END;

DROP PROCEDURE GetGenreID;
GO

CREATE PROCEDURE GetGenreID(@id INT, @G_id INT OUTPUT) AS
BEGIN
	SET @G_id = (SELECT GenreID FROM GroupDB
			   WHERE GroupID = @id)
END;

SELECT * FROM GroupDB join GenreDB on GroupDB.GroupID = GenreDB.GenreID